# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sue's Paws | Dog Grooming Nottingham
email: suespaws@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sue's Paws is an independant, professional dog groomer in Nottingham
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.suespaws.co.uk" # the base hostname & protocol for your site
facebook: suespaws
instagram: suespaws 
permalink: pretty
tel: "07966 584 581"
# Build settings
markdown: kramdown 
